Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'e0ec-154-247-168-211.ngrok-free.app'. You may need to add 'e0ec-154-247-168-211.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e0ec-154-247-168-211.ngrok-free.app'. You may need to add 'e0ec-154-247-168-211.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /user_management/google_sign_in
F:\pest_detection_app_backend\pest_detection_backend\pest_detection_backend\settings.py changed, reloading.
Watching for file changes with StatReloader
Invalid HTTP_HOST header: 'e0ec-154-247-168-211.ngrok-free.app'. You may need to add 'e0ec-154-247-168-211.ngrok-free.app' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "F:\pest_detection_app_backend\pestvenv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e0ec-154-247-168-211.ngrok-free.app'. You may need to add 'e0ec-154-247-168-211.ngrok-free.app' to ALLOWED_HOSTS.
Bad Request: /user_management/google_sign_in
F:\pest_detection_app_backend\pest_detection_backend\pest_detection_backend\settings.py changed, reloading.
